name: Echo Username

on:
  push:

jobs:
  say-username:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo GitHub actor
        run: echo "Username is ${{ github.actor }}"
